@startmindmap
-[#Pink] ソリューション\nアーキテクト\nアソシエイト

--[#Orange] 1. 弾力性に優れた\nアーキテクチャの設計 [30%]
--- 1.1 多層アーキテクチャソリューション
--- 1.2 高可用性/フォールトトレラントアーキテクチャ
--- 1.3 デカップリングメカニズム
---- コンポーネントの疎結合化
----- SQS
--- 1.4 耐障害性の高いストレージ

--[#Orange] 2. 高性能アーキテクチャ\nの設計 [28%]
--- 2.1 伸縮自在でスケーラブルな\nコンピューティングソリューション
--- 2.2 ハイパフォーマンスでスケーラブルな\nストレージソリューション
--- 2.3 ハイパフォーマンスな\nネットワークソリューション
--- 2.4 ハイパフォーマンスな\nデータベースソリューション

++[#Orange] 3. セキュアなアプリケーションと\nアーキテクチャの設計 [24%]
+++ 3.1 セキュアなアクセス設計
++++ IAM
+++ 3.2 セキュアなアプリケーション階層
++++ セキュリティグループ
++++ ネットワークACL
++++ サブネット
++++ ルーティングメカニズム
++++ 外部脅威からの保護
+++ 3.3 データセキュリティ

++[#Orange] 4. コストを最適化した\nアーキテクチャの設計 [18%]
+++ 4.1 コスト効率の高い\nストレージソリューション
+++ 4.2 費用対効果の高い\nコンピューティング/データベースサービス
+++ 4.3 コストを最適化した\nネットワークアーキテクチャ

@endmindmap