@startmindmap
-[#Pink] AWSクラウド\nプラクティショナー

--[#Orange] クラウドの概念（26%）
--- クラウドコンピューティングとは
---- クラウド型
---- オンプレミス型
---- ハイブリット型
----- AWS Outposts
----- Direct Connect
--- クラウドコンピューティングの6つの利点
--- Well-Architectedフレームワーク
---- 5つの柱
---- 11のベストプラクティス

--[#Orange] セキュリティと\nコンプライアンス（25%）
--- 責任共有モデル
---- 顧客とAWSの責任分界点

--- ユーザーアクセス
---- ルートユーザー
---- IAM
----- IAMアイデンティティ
------ IAMユーザー
------ IAMロール
------ IAMグループ
----- IAMポリシー
----- IDフェデレーション
----- MFA

--- AWS Organizations
---- 組織単位(OU)
---- サービスコントロールポリシー(SCP)

--- コンプライアンス
---- AWS Artifact
----- Artifact Reports
----- Artifact Agreements
---- カスタマーコンプライアンスセンター

--- クラッキング対策
---- セキュリティグループ
---- ELB
---- AWS Shield
---- AWS WAF

--- データ暗号化
---- AWS KMS
---- CloudHSM

--- 評価/分析
---- Inspector
---- GuardDrty

--[#Orange] 料金と請求（16%）
--- 料金
---- 無料利用枠
---- 料金体系の仕組み
---- 料金計算ツール

--- 請求
---- 請求とコスト管理ダッシュボード
---- コンソリデーティッドビリング（一括請求）
---- AWS Budgets
---- AWS Cost Explorer
---- Saving Plansの購入・管理

--- サポートプラン
---- AWS Personal Health Dashboard
---- テクニカルアカウントマネージャー (TAM)
--- AWS Marketplace

++[#Orange] テクノロジー（33%）
+++ クローバルインフラクトラクチャ
++++ リージョン
++++ アベイラビリティゾーン
++++ エッジロケーション

+++ プロビジョニングとデプロイ
++++ マネージメントコンソール
++++ コマンドラインインターフェース(CLI)
++++ CloudFormation
++++ OpsWorks
++++ Elastic Beanstalk

+++ ネットワーク
++++ VPC
+++++ サブネット
+++++ ネットワークACL
+++++ セキュリティグループ
++++ インターネットゲートウェイ
++++ 仮想プライベートゲートウェイ
++++ Direct Connect
++++ VPCピアリング
++++ NATゲートウェイ
++++ コンテンツ配信サービス
+++++ Route 53
+++++ CloudFront

+++ コンピューティング
++++ EC2
+++++ インスタンスストア
+++++ AMI
++++ スケーラビリティ
+++++ ELB
+++++ Auto Scaling

++++ メッセージング/キューイング
+++++ SNS
+++++ SQS

++++ ECS
++++ Lambda

+++ ストレージ
++++ EBS
++++ S3
+++++ S3 Gateway
++++ EFS

+++ データベース
++++ RDS
++++ Aurora
++++ Redshift
++++ DynanmoDB

+++ モニタリング/運用
++++ CloudWatch
++++ CloudTrail
++++ Trusted Advisor
++++ Systems Manager

+++ AWSへの移行
++++ Cloud Adoption Framework (CAF)
++++ 6つのR
++++ Snowファミリー

@endmindmap
