@startmindmap
-[#Pink] Well-Architected\nフレームワーク

--[#Orange] Reliability\n（信頼性）
--- 弾力性・柔軟さ
---- 1.スケーラビリティの確保
---- 2.環境の自動化
--- 一貫性
---- 4.コンポーネントの疎結合
---- 8.単一障害点(SPOF)の排除

--[#Orange] 安全性\n(Security)
--- 11.セキュリティの確保

--[#Orange] Operational Excellence\n（運用上の優秀性）
--- 2.環境の自動化

++[#Orange] パフォーマンス効率\n(Performance Efficiency)
+++ 1.スケーラビリティの確保
+++ 3.使い捨てリソースの使用
+++ 5.サーバーレス
+++ 6.最適なデータベースの選択
+++ 7.増大するデータ量の対応
+++ 10.キャッシュの利用

++[#Orange] コスト最適化\n(Cost Optimization)
+++ 9.コスト最適化

@endmindmap
