@startmindmap "exam-coverage"

-[#Pink] Machine Learning\nEngineer\nAssociate

--[#Orange] 1. 機械学習 (ML) の\nためのデータ準備 [28%]
--- 1.1 データを取り込んで保存する
--- 1.2 データを変換し、\n特徴量エンジニアリングを実行する
--- 1.3 データの完全性を確保し、\nモデリングに向けてデータを準備する

--[#Orange] 2. ML モデルの\n開発 [26%]
--- 2.1 モデリングアプローチを選択する
--- 2.2 ML モデルをトレーニングする
--- 2.3 ML モデルのパフォーマンスを\n分析する

++[#Orange] 3. ML ワークフローの\nデプロイと\nオーケストレーション [22%]
+++ 3.1 デプロイのための\nML モデルをパッケージ化する
+++ 3.2 ML インフラストラクチャを\nデプロイおよびオーケストレーションする
+++ 3.3 ML ワークフローを\n自動化する

++[#Orange] 4. ML ソリューションの\nモニタリング、保守、\nセキュリティ [24%]
+++ 4.1 ML インフラストラクチャを\nモニタリングする
+++ 4.2 モデルパフォーマンスを\nモニタリングする
+++ 4.3 ML ソリューションの\nセキュリティを確保する

@endmindmap
